### ISSUE TITLE
server.js

### ISSUE THREAD

**Issue by ghost** [brahmay/codeacademy-project-3-the-scoop#7]
https://github.com/brahmay/codeacademy/blob/master/capstone-project-2-expresso/server.js

This a very nicely organized entry point to your application. Good job setting up appropriate request parsing, cors, error handling, and router middleware. 👍 

Consider throwing in some logging middleware and some comments just to have a little documentation to make your code easier to understand.

**Comment by brahmay** [comment]
Thank You for the feedback.
