### ISSUE TITLE
API

### ISSUE THREAD

**Issue by ghost** [brahmay/codeacademy-project-3-the-scoop#9]
https://github.com/brahmay/codeacademy/tree/master/capstone-project-2-expresso/api

Great job breaking your API down into multiple routers to keep your API as modular as possible. This is a great way to keep your routes independently organized, maintainable, and testable. 👍 

https://github.com/brahmay/codeacademy/blob/master/capstone-project-2-expresso/api/employee.js#L123

Subrouters help remove repetition from your route paths and that's one less place where you could potentially introduce a bug to your application. Nice 👌 

You've applied a lot (or all) of the most important concepts from the Express unit into this API and have kept your code very well organized. Awesome job 🚀

**Comment by brahmay** [comment]
Thank You
